apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-crud
  template:
    metadata:
      labels:
        app: go-crud
    spec:
      containers:
        - name: go-crud
          image: sha256:0bb76dd7df73932c2695869f939a07b73e6e3aef36c5f9196261dc6362b9ffbb
          ports:
            - containerPort: 8000
