apiVersion: v1
kind: Service
metadata:
  name: my-app-canary-service
spec:
  type: LoadBalancer
  selector:
    app: my-app
    version: canary
  ports:
    - protocol: TCP
      port: 80        # Порт для зовнішнього доступу
      targetPort: 8000  # Порт вашого додатка всередині контейнера
