// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"example.com/m/config"
	"example.com/m/internal/database"
)

// Injectors from wire.go:

func InitializeUserHandler() *Handler {
	configConfig := config.ProvideConfig()
	db := database.ProvideDatabase(configConfig)
	service := ProvideUserService(db)
	handler := ProvideUserHandler(service)
	return handler
}
