name: ARGO

on:
  push:
    branches:
      - main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ruslanmaistrenko
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ruslanmaistrenko/my_image:latest .
          docker push ruslanmaistrenko/my_image:latest


  update-helm-chart:
    needs: docker-build-push
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Update Helm chart with new image tag
      - name: Update Helm Chart with new image tag
        run: |
          sed -i 's|image: ruslanmaistrenko/my_image:.*|image: ruslanmaistrenko/my_image:latest|' ./values.yaml
          git add ./values.yaml
          git commit -m "Update Helm chart with new image version"
          git push

  sync-argocd:
    needs: update-helm-chart
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to ArgoCD
      - name: Login to ArgoCD
        run: |
          argocd login localhost:8081 --username admin --password dojCecnCPHGsi-Nt --insecure

      # Sync application in ArgoCD
      - name: Sync ArgoCD application
        run: |
          argocd app sync go-crud --auth-token ${{ secrets.ARGOCD_TOKEN }}
