name: CI for Go CRUD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ruslanmaistrenko/my_image:latest .

      - name: Push Docker image to DockerHub
        run: |
          docker push ruslanmaistrenko/my_image:latest
          docker push ruslanmaistrenko/my_image:${{ github.sha }}

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Update Helm chart with new Docker image tag
        run: |
          helm repo add my-helm-repo https://my-repo-url
          helm repo update
          helm upgrade --install go-crud my-helm-repo/go-crud --set image.tag=latest

      - name: Sync ArgoCD application
        run: |
          argocd app sync go-crud --auth-token ${{ secrets.ARGOCD_TOKEN }}

