name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: 1111
          MYSQL_DATABASE: go_crud_api

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      # Ensure go.mod exists
      - name: Initialize Go modules
        run: |
          if [ ! -f go.mod ]; then
            go mod init example.com/myproject
          fi

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Install migrate tool
      - name: Install migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz -o migrate.tar.gz
          tar -xvf migrate.tar.gz
          chmod +x migrate
          sudo mv migrate /usr/local/bin/

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h127.0.0.1 -u root -p1111 --silent; then
              break
            fi
            echo "Waiting for MySQL..."
            sleep 3
          done

      # Run migrations
      - name: Run migrations
        run: migrate -path ./migrations -database "mysql://root:1111@tcp(127.0.0.1:3306)/go_crud_api" up

      # Run integration tests
      - name: Run tests
        working-directory: ./tests/integration
        env:
          DB_USER: root
          DB_PASSWORD: 1111
          DB_NAME: go_crud_api
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
        run: go test ./... -v